; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 44/0.1.0; intrinsic ABI: v1; catalog SHA-256: 7614853209eaad408a472d100c764487d0f76e0c245bed8904a44720037f4e0b.
; LLVM source: 1cb4e3833c1919c2e6fb579a23ac0e2b22587b7e.

target triple = "nvptx64-nvidia-cuda"

define i32 @probe_add_f16x2(i32 %arg0, i32 %arg1) {
  %result = call i32 asm "add.rn.f16x2 $0, $1, $2;", "=r,r,r"(i32 %arg0, i32 %arg1)
  ret i32 %result
}
