; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 20bc41c2ab93828b7f97b6ee90efccfc118317a590803216a3a045b1c2879889.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

declare i32 @llvm.nvvm.read.ptx.sreg.ntid.z()

define i32 @probe_block_dim_z() {
  %result = call i32 @llvm.nvvm.read.ptx.sreg.ntid.z()
  ret i32 %result
}

