; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 104ec2f5251c7dd211ed7547f34a7434e1aea67c4abd928d971784f1e81217d5.
; LLVM source: 1cb4e3833c1919c2e6fb579a23ac0e2b22587b7e.

target triple = "nvptx64-nvidia-cuda"

declare i32 @llvm.nvvm.read.ptx.sreg.nclusterid.x()

define i32 @probe_cluster_grid_dim_x() {
  %result = call i32 @llvm.nvvm.read.ptx.sreg.nclusterid.x()
  ret i32 %result
}

