; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 90f843cce5f56a1499b53ac77a837864c9c04e091becb9a950a0aef2aae2a31a.
; LLVM source: 1cb4e3833c1919c2e6fb579a23ac0e2b22587b7e.

target triple = "nvptx64-nvidia-cuda"

declare void @llvm.nvvm.cp.async.bulk.tensor.reduce.min.im2col.3d(ptr addrspace(3), ptr, i32, i32, i32, i64, i1) #0

define void @probe_cp_async_bulk_tensor_reduce_min_im2col_3d(ptr %src_generic, ptr %tensor_map, i32 %coord0, i32 %coord1, i32 %coord2) #0 {
  %src = addrspacecast ptr %src_generic to ptr addrspace(3)
  call void @llvm.nvvm.cp.async.bulk.tensor.reduce.min.im2col.3d(ptr addrspace(3) %src, ptr %tensor_map, i32 %coord0, i32 %coord1, i32 %coord2, i64 0, i1 false) #0
  ret void
}

attributes #0 = { convergent }
