; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 104ec2f5251c7dd211ed7547f34a7434e1aea67c4abd928d971784f1e81217d5.
; LLVM source: 1cb4e3833c1919c2e6fb579a23ac0e2b22587b7e.

target triple = "nvptx64-nvidia-cuda"

declare i32 @llvm.nvvm.f2tf32.rz.satfinite(float)

define i32 @probe_cvt_rz_satfinite_tf32_f32(float %value) {
  %result = call i32 @llvm.nvvm.f2tf32.rz.satfinite(float %value)
  ret i32 %result
}
