; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 44/0.1.0; intrinsic ABI: v1; catalog SHA-256: e81d4caea6226d9623137fa3154740890712df45977d7a8dc17ca3046e33fdae.
; LLVM source: 1cb4e3833c1919c2e6fb579a23ac0e2b22587b7e.

target triple = "nvptx64-nvidia-cuda"

declare float @llvm.nvvm.div.rn.f(float, float)

define float @probe_div_rn_f32(float %arg0, float %arg1) {
  %result = call float @llvm.nvvm.div.rn.f(float %arg0, float %arg1)
  ret float %result
}
