; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 20bc41c2ab93828b7f97b6ee90efccfc118317a590803216a3a045b1c2879889.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

define i32 @probe_dsmem_read_u32(ptr %source_generic, i32 %rank) #0 {
  %source = addrspacecast ptr %source_generic to ptr addrspace(3)
  %value = call i32 asm sideeffect "{ .reg .u64 %mapped; mapa.shared::cluster.u64 %mapped, $1, $2; ld.shared::cluster.u32 $0, [%mapped]; }", "=r,l,r,~{memory}"(ptr addrspace(3) %source, i32 %rank) #0
  ret i32 %value
}

attributes #0 = { convergent }
