; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 00372dfe2e27296fcd2a4505eff6e547153693b60a4fcc0d1599a4d589193226.
; LLVM source: 1cb4e3833c1919c2e6fb579a23ac0e2b22587b7e.

target triple = "nvptx64-nvidia-cuda"

declare float @llvm.nvvm.fma.rm.ftz.f(float, float, float)

define float @probe_fma_rm_ftz_f32(float %arg0, float %arg1, float %arg2) {
  %result = call float @llvm.nvvm.fma.rm.ftz.f(float %arg0, float %arg1, float %arg2)
  ret float %result
}
