; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 44/0.1.0; intrinsic ABI: v1; catalog SHA-256: e81d4caea6226d9623137fa3154740890712df45977d7a8dc17ca3046e33fdae.
; LLVM source: 1cb4e3833c1919c2e6fb579a23ac0e2b22587b7e.

target triple = "nvptx64-nvidia-cuda"

declare i32 @llvm.nvvm.read.ptx.sreg.lanemask.gt()

define i32 @probe_lanemask_gt() {
  %result = call i32 @llvm.nvvm.read.ptx.sreg.lanemask.gt()
  ret i32 %result
}

