; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 44/0.1.0; intrinsic ABI: v1; catalog SHA-256: e81d4caea6226d9623137fa3154740890712df45977d7a8dc17ca3046e33fdae.
; LLVM source: 1cb4e3833c1919c2e6fb579a23ac0e2b22587b7e.

target triple = "nvptx64-nvidia-cuda"

define ptr addrspace(3) @probe_map_shared_rank(ptr %source_generic, i32 %rank) #0 {
  %source = addrspacecast ptr %source_generic to ptr addrspace(3)
  %mapped_integer = call i64 asm sideeffect "mapa.shared::cluster.u64 $0, $1, $2;", "=l,l,r"(ptr addrspace(3) %source, i32 %rank) #0
  %mapped = inttoptr i64 %mapped_integer to ptr addrspace(3)
  ret ptr addrspace(3) %mapped
}

attributes #0 = { convergent }
