; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 104ec2f5251c7dd211ed7547f34a7434e1aea67c4abd928d971784f1e81217d5.
; LLVM source: 1cb4e3833c1919c2e6fb579a23ac0e2b22587b7e.

target triple = "nvptx64-nvidia-cuda"

declare void @llvm.nvvm.mbarrier.inval.shared(ptr addrspace(3))

define void @probe_mbarrier_inval(ptr %barrier_generic) {
  %barrier = addrspacecast ptr %barrier_generic to ptr addrspace(3)
  call void @llvm.nvvm.mbarrier.inval.shared(ptr addrspace(3) %barrier)
  ret void
}
