; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 44/0.1.0; intrinsic ABI: v1; catalog SHA-256: 7614853209eaad408a472d100c764487d0f76e0c245bed8904a44720037f4e0b.
; LLVM source: 1cb4e3833c1919c2e6fb579a23ac0e2b22587b7e.

target triple = "nvptx64-nvidia-cuda"

declare i32 @llvm.nvvm.redux.sync.umax(i32, i32)

define i32 @probe_redux_sync_max_u32(i32 %member_mask, i32 %value) {
  %result = call i32 @llvm.nvvm.redux.sync.umax(i32 %value, i32 %member_mask)
  ret i32 %result
}
