; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 90f843cce5f56a1499b53ac77a837864c9c04e091becb9a950a0aef2aae2a31a.
; LLVM source: 1cb4e3833c1919c2e6fb579a23ac0e2b22587b7e.

target triple = "nvptx64-nvidia-cuda"

; LLVM source: llvm.nvvm.tcgen05.commit.cg1; route: inline PTX; source contract: TablegenSelectionChangesPtx
define void @probe_tcgen05_commit(i32 %mbar) #0 {
  call void asm sideeffect "tcgen05.commit.cta_group::1.mbarrier::arrive::one.b64 [$0];", "r,~{memory}"(i32 %mbar) #0
  ret void
}

attributes #0 = { convergent }
