; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 44/0.1.0; intrinsic ABI: v1; catalog SHA-256: 7614853209eaad408a472d100c764487d0f76e0c245bed8904a44720037f4e0b.
; LLVM source: 1cb4e3833c1919c2e6fb579a23ac0e2b22587b7e.

target triple = "nvptx64-nvidia-cuda"

; LLVM source: llvm.nvvm.tcgen05.fence.before.thread.sync; route: inline PTX; source contract: ExactTablegenSelection
define void @probe_tcgen05_fence_before_thread_sync() #0 {
  call void asm sideeffect "tcgen05.fence::before_thread_sync;", "~{memory}"() #0
  ret void
}

attributes #0 = { convergent }
