; SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
; SPDX-License-Identifier: Apache-2.0
; @generated by cuda-intrinsics-gen 0.1.0. DO NOT EDIT.
; Catalog schema/version: 46/0.1.0; intrinsic ABI: v1; catalog SHA-256: 49bcd626b91f3261e80f77fb2817a54d96bddd6364f2564d113eee7ee62b8266.
; LLVM source: 16696adcd119e6ba9cc175207d984d7021211acb.

target triple = "nvptx64-nvidia-cuda"

define void @probe_tensormap_replace_rank(ptr %tensor_map, i32 %new_value) {
  call void asm sideeffect "tensormap.replace.tile.rank.global.b1024.b32 [$0], $1;", "l,r,~{memory}"(ptr %tensor_map, i32 %new_value)
  ret void
}
