/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

use crate::render::all_outputs;
use crate::resolve::resolve;
use crate::util::{check_contents, pretty_json, rustfmt_source, sha256_bytes, write_if_changed};
use anyhow::Result;
use std::collections::BTreeSet;
use std::fs;
use std::path::{Path, PathBuf};

const MANAGED_GENERATED_ROOTS: &[&str] = &[
    "crates/cuda-intrinsics/src/generated",
    "crates/cuda-device/src/generated",
    "crates/cuda-oxide-codegen/src",
    "crates/dialect-nvvm/src/ops/generated",
    "crates/mir-importer/src/translator/terminator/intrinsics",
    "crates/mir-importer/src",
    "crates/mir-lower/src/convert",
    "crates/rustc-codegen-cuda/src",
    "intrinsics/probes",
];
const GENERATED_MARKER: &[u8] = b"@generated by cuda-intrinsics-gen";

pub fn run(repo_root: &Path, check: bool) -> Result<()> {
    let catalog = resolve(repo_root)?;
    let catalog_json = pretty_json(&catalog)?;
    let catalog_hash = sha256_bytes(catalog_json.as_bytes());
    let mut outputs = all_outputs(&catalog, catalog_json, &catalog_hash)?;
    let expected: BTreeSet<PathBuf> = outputs.keys().cloned().collect();
    for (path, contents) in &mut outputs {
        if path.extension().and_then(|extension| extension.to_str()) == Some("rs") {
            *contents = rustfmt_source(contents)?;
        }
    }
    let mut changed = 0usize;
    for (relative, contents) in outputs {
        let path = repo_root.join(relative);
        if check {
            check_contents(&path, &contents)?;
        } else if write_if_changed(&path, &contents)? {
            changed += 1;
            println!("wrote {}", path.display());
        }
    }
    for relative in stale_generated_outputs(repo_root, &expected)? {
        let path = repo_root.join(&relative);
        if check {
            anyhow::bail!(
                "stale managed generated output remains at {}; run cuda-intrinsics-gen generate",
                path.display()
            );
        } else {
            fs::remove_file(&path)?;
            changed += 1;
            println!("removed stale {}", path.display());
        }
    }
    if check {
        println!("generated intrinsic outputs are current");
    } else if changed == 0 {
        println!("generated intrinsic outputs were already current");
    } else {
        println!("updated {changed} generated intrinsic outputs");
    }
    Ok(())
}

fn stale_generated_outputs(repo_root: &Path, expected: &BTreeSet<PathBuf>) -> Result<Vec<PathBuf>> {
    let mut stale = Vec::new();
    for relative_root in MANAGED_GENERATED_ROOTS {
        let root = repo_root.join(relative_root);
        if root.is_dir() {
            collect_stale_generated(repo_root, &root, expected, &mut stale)?;
        }
    }
    stale.sort();
    stale.dedup();
    Ok(stale)
}

fn collect_stale_generated(
    repo_root: &Path,
    directory: &Path,
    expected: &BTreeSet<PathBuf>,
    stale: &mut Vec<PathBuf>,
) -> Result<()> {
    for entry in fs::read_dir(directory)? {
        let entry = entry?;
        let path = entry.path();
        let file_type = entry.file_type()?;
        if file_type.is_dir() {
            collect_stale_generated(repo_root, &path, expected, stale)?;
        } else if file_type.is_file() {
            let bytes = fs::read(&path)?;
            if bytes
                .windows(GENERATED_MARKER.len())
                .any(|window| window == GENERATED_MARKER)
            {
                let relative = path.strip_prefix(repo_root)?.to_path_buf();
                if !expected.contains(&relative) {
                    stale.push(relative);
                }
            }
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::time::{SystemTime, UNIX_EPOCH};

    #[test]
    fn unexpected_marker_bearing_file_is_stale() {
        let unique = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        let root = std::env::temp_dir().join(format!(
            "cuda-intrinsics-gen-stale-{}-{unique}",
            std::process::id()
        ));
        let directory = root.join("intrinsics/probes");
        fs::create_dir_all(&directory).unwrap();
        fs::write(
            directory.join("removed.ll"),
            "; @generated by cuda-intrinsics-gen test\n",
        )
        .unwrap();

        let stale = stale_generated_outputs(&root, &BTreeSet::new()).unwrap();
        assert_eq!(stale, [PathBuf::from("intrinsics/probes/removed.ll")]);
        fs::remove_dir_all(root).unwrap();
    }
}
